version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "docker"

- package-ecosystem: "javascript"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "javascript"
