version: '3'

vars:
  ADMIN_MAIL: '{{ .ADMIN_MAIL | default "admin@example.org" }}'
  ADMIN_ORG:  '{{ .ADMIN_ORG  | default "example.org" }}'
  ADMIN_PASS: '{{ .ADMIN_PASS | default "password123" }}'

includes:
  docker: Taskfile.docker.yaml

tasks:
  default:
    cmds:
    - task: docker:build
    - task: docker:admin
    - task: docker:watch
