apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: redis
        image: redis
        args:
        - --loglevel
        - warning
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 2
          periodSeconds: 10
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: redis
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
